# Generated by Django 3.1 on 2020-09-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_auto_20200909_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='jos', max_length=250),
            preserve_default=False,
        ),
    ]
