# Generated by Django 3.1 on 2020-08-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_bloodrequest'),
        ('bloodrequestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='request',
            field=models.ManyToManyField(related_name='group_request', to='bloodapp.BloodRequest'),
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
    ]
