# Generated by Django 3.1 on 2020-09-11 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodrequestapp', '0002_auto_20200909_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL, verbose_name='receipient'),
        ),
    ]
